### ISSUE TITLE
java.lang.NullPointerException: Attempt to read from field 'android.os.MessageQueue android.os.Looper.mQueue' on a null object reference when trying init Infobip inside service

### ISSUE THREAD

**Issue by finchatticus** [infobip/mobile-messaging-sdk-android#20]
Using version 3.0.3
Trying init infobip inside firebase service:
`
MobileMessaging.Builder(app)
                .withMessageStore(SQLiteMessageStore::class.java)
                .withDisplayNotification(
                    NotificationSettings.Builder(app)
                        .withMultipleNotifications()
                        .withCallbackActivity(MainActivity::class.java)
                        .withDefaultIcon(R.drawable.ic_push)
                        .build()
                )
                .build()
`

Got exception:
`java.lang.NullPointerException: Attempt to read from field 'android.os.MessageQueue android.os.Looper.mQueue' on a null object reference
at android.os.Handler.<init>(Handler.java:233)
at android.os.Handler.<init>(Handler.java:141)
at android.telephony.PhoneStateListener$1.<init>(PhoneStateListener.java:301)
at android.telephony.PhoneStateListener.<init>(PhoneStateListener.java:301)
at android.telephony.PhoneStateListener.<init>(PhoneStateListener.java:271)
at org.infobip.mobile.messaging.telephony.MobileNetworkStateListener.<init>(MobileNetworkStateListener.java:15)
at org.infobip.mobile.messaging.MobileMessagingCore$Builder.build(MobileMessagingCore.java:1976)
at org.infobip.mobile.messaging.MobileMessaging$Builder.build(MobileMessaging.java:860)
at org.infobip.mobile.messaging.MobileMessaging$Builder.build(MobileMessaging.java:827)`

See StackOverflow:
https://stackoverflow.com/questions/32568328/nullpointerexecption-when-calling-a-phonestatelistener-in-a-service
https://stackoverflow.com/questions/41008436/android-phonestatelistener-constructor-reflection
https://stackoverflow.com/questions/28675007/android-phonestatelistener-runs-on-the-main-thread
https://stackoverflow.com/questions/61880560/calling-phonestatelistener-in-a-thread-inside-a-service

**Comment by riskpp** [comment]
Hi, @finchatticus, thank you for reporting it, we will check!

**Comment by finchatticus** [comment]
Hi! @riskpp are you check?

**Comment by riskpp** [comment]
Hi, @finchatticus 
Thank you for the provided links. We still have a question to understand the need of this change. MobileMessaging.Builder is supposed to be called from Activity. Could you please explain what are the reasons to call it from FirebaseMessagingService?

**Comment by finchatticus** [comment]
@riskpp In our case, it a singleton and its initialized by Kodein DI when received push

**Comment by finchatticus** [comment]
what about this issue?

**Comment by tjuric** [comment]
Hi @finchatticus,
Sorry for the delayed response. 

This issue was low on our priority list after we got information from you about DI that you use. Are you still experiencing the same issue?

**Comment by tjuric** [comment]
Closing due to inactivity.
