### ISSUE TITLE
org.infobip.mobile.messaging.api.support.ApiException: 24, Chat widget not found [10024]

### ISSUE THREAD

**Issue by mrdafian47** [infobip/mobile-messaging-sdk-android#22]
Here, i got error when call the function of InApp...

The log
```
D/MMHTTP: REQUEST: Request(httpMethod=GET, uri=https://mobile.infobip.com/mobile/1/chat/widget, apiKey=37f2c0096f81cb80833e58e4ca657fd0-f7601e6b-b0c5-4104-a5c1-fc73a069cf34, credentials=null, headers={applicationcode=[6e8a618b55], pushregistrationid=[28a3c86a-db78-4420-b10a-aaa3db6ea51e], foreground=[true], sessionId=[28a3c86a-db78-4420-b10a-aaa3db6ea51e_1604546228096], installationid=[6c3ea405-5161-4131-a1f9-cc7cf1c2106c]}, queryParams={}, body=null)
I/Choreographer: Skipped 42 frames!  The application may be doing too much work on its main thread.
I/OpenGLRenderer: Davey! duration=720ms; Flags=0, IntendedVsync=296852502038652, Vsync=296853202038624, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=296853211546361, AnimationStart=296853211687038, PerformTraversalsStart=296853213082975, DrawStart=296853213490580, SyncQueued=296853215152350, SyncStart=296853215229173, IssueDrawCommandsStart=296853215315111, SwapBuffers=296853219049746, FrameCompleted=296853222117819, DequeueBufferDuration=327000, QueueBufferDuration=543000, 
D/MMHTTP: REQUEST: Request(httpMethod=POST, uri=https://mobile.infobip.com/mobile/5/messages, apiKey=37f2c0096f81cb80833e58e4ca657fd0-f7601e6b-b0c5-4104-a5c1-fc73a069cf34, credentials=null, headers={applicationcode=[6e8a618b55], pushregistrationid=[28a3c86a-db78-4420-b10a-aaa3db6ea51e], foreground=[true], sessionId=[28a3c86a-db78-4420-b10a-aaa3db6ea51e_1604546228096], installationid=[6c3ea405-5161-4131-a1f9-cc7cf1c2106c]}, queryParams={platformType=[GCM]}, body=null)
W/ata.android.de: Accessing hidden field Ljava/nio/Buffer;->address:J (light greylist, reflection)
D/FA: Connected to remote service
D/MobileMessaging: org.infobip.mobile.messaging.api.support.ApiException: 24, Chat widget not found [10024]
        at org.infobip.mobile.messaging.api.support.http.client.DefaultApiClient.executeHTTP(DefaultApiClient.java:195)
        at org.infobip.mobile.messaging.api.support.http.client.DefaultApiClient.execute(DefaultApiClient.java:86)
        at org.infobip.mobile.messaging.api.support.Generator$CachingInvocationHandler.invoke(Generator.java:368)
        at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
        at $Proxy5.getWidgetConfiguration(Unknown Source)
        at org.infobip.mobile.messaging.chat.mobileapi.InAppChatSynchronizer$1.run(InAppChatSynchronizer.java:67)
        at org.infobip.mobile.messaging.chat.mobileapi.InAppChatSynchronizer$1.run(InAppChatSynchronizer.java:62)
        at org.infobip.mobile.messaging.mobileapi.common.MRetryableTask$1.run(MRetryableTask.java:82)
        at org.infobip.mobile.messaging.mobileapi.common.MAsyncTask$2.doInBackground(MAsyncTask.java:55)
        at org.infobip.mobile.messaging.mobileapi.common.MAsyncTask$2.doInBackground(MAsyncTask.java:43)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
D/MMHTTP: REQUEST: Request(httpMethod=GET, uri=https://mobile.infobip.com/mobile/1/chat/widget, apiKey=37f2c0096f81cb80833e58e4ca657fd0-f7601e6b-b0c5-4104-a5c1-fc73a069cf34, credentials=null, headers={applicationcode=[6e8a618b55], pushregistrationid=[28a3c86a-db78-4420-b10a-aaa3db6ea51e], foreground=[true], sessionId=[28a3c86a-db78-4420-b10a-aaa3db6ea51e_1604546228096], installationid=[6c3ea405-5161-4131-a1f9-cc7cf1c2106c]}, queryParams={}, body=null)
D/MobileMessaging: org.infobip.mobile.messaging.api.support.ApiException: 24, Chat widget not found [10024]
        at org.infobip.mobile.messaging.api.support.http.client.DefaultApiClient.executeHTTP(DefaultApiClient.java:195)
        at org.infobip.mobile.messaging.api.support.http.client.DefaultApiClient.execute(DefaultApiClient.java:86)
        at org.infobip.mobile.messaging.api.support.Generator$CachingInvocationHandler.invoke(Generator.java:368)
        at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
        at $Proxy5.getWidgetConfiguration(Unknown Source)
        at org.infobip.mobile.messaging.chat.mobileapi.InAppChatSynchronizer$1.run(InAppChatSynchronizer.java:67)
        at org.infobip.mobile.messaging.chat.mobileapi.InAppChatSynchronizer$1.run(InAppChatSynchronizer.java:62)
        at org.infobip.mobile.messaging.mobileapi.common.MRetryableTask$1.run(MRetryableTask.java:82)
        at org.infobip.mobile.messaging.mobileapi.common.MAsyncTask$2.doInBackground(MAsyncTask.java:55)
        at org.infobip.mobile.messaging.mobileapi.common.MAsyncTask$2.doInBackground(MAsyncTask.java:43)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
D/SharedPreferencesImpl: Time required to fsync /data/user/0/com.rata.android.dev/shared_prefs/com.rata.android.dev_preferences.xml: [<1: 0, <2: 0, <4: 0, <8: 6, <16: 7, <32: 3, <64: 6, <128: 0, <256: 1, <512: 1, <1024: 0, <2048: 0, <4096: 0, <8192: 0, <16384: 0, >=16384: 0]
```

My MainActivity.kt
```
class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        InAppChat.getInstance(this).activate()

        setContentView(R.layout.activity_main)

        val userIdentity = UserIdentity()
        userIdentity.externalUserId = "900657308723"
        userIdentity.phones = setOf("79210000000")
        userIdentity.emails = setOf("dummy@gmail.com")

        val userAttributes = UserAttributes()
        userAttributes.firstName = "test1"
        userAttributes.lastName = "test2"

        MobileMessaging.getInstance(this).personalize(userIdentity, null, object : MobileMessaging.ResultListener<User>() {
            override fun onResult(result: Result<User, MobileMessagingError>?) {

                // Code
            }
        })

        findViewById<Button>(R.id.bt_chat).setOnClickListener {

            // Trigger error here
            InAppChat.getInstance(this).inAppChatView().show()
        }
    }
}
```

My app/build.gradle
```
plugins {
    id 'com.android.application'
    id 'com.google.gms.google-services'
    id 'kotlin-android'
}

android {
    compileSdkVersion 29
    buildToolsVersion "30.0.2"

    defaultConfig {
        applicationId "com.dummy.android.dev"
        minSdkVersion 19
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {

    implementation platform('com.google.firebase:firebase-bom:26.0.0')
    implementation 'com.google.firebase:firebase-analytics-ktx'
    implementation 'com.google.firebase:firebase-messaging-ktx'

    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation 'androidx.core:core-ktx:1.3.2'
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'com.google.android.material:material:1.2.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.2'

    implementation ('org.infobip.mobile.messaging.api:infobip-mobile-messaging-android-sdk:4.0.2@aar') {
        transitive = true
    }
    implementation "org.infobip.mobile.messaging.api:infobip-mobile-messaging-android-chat-sdk:4.+@aar"

    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
}
```

**Comment by riskpp** [comment]
@mohamad-rizki Please check that you followed this instruction https://www.infobip.com/docs/live-chat/mobile-in-app-chat-quick-start and linked application profile to the live-chat. Also be aware that starting from 4.0.0 version method for activation of in-app chat service should be called after initializing MobileMessaging SDK
`InAppChat.getInstance(context).activate();`

**Comment by mrdafian47** [comment]
Sure, initializing MobileMessaging SDK should be done. I put those code in Application class ( like the sample code in demo module )

```
class BaseApplication : Application() {

    override fun onCreate() {
        super.onCreate()
        MobileMessaging.Builder(this)
                .withDisplayNotification(NotificationSettings.Builder(this)
                        .withMultipleNotifications()
                        .withDefaultIcon(android.R.drawable.ic_notification_overlay)
                        .withColor(ContextCompat.getColor(this, R.color.purple_700))
                        .build())
                .build()
    }
}
```

> linked application profile to the live-chat

Can you elaborate the meaning about that @riskpp  ?

**Comment by riskpp** [comment]
> Can you elaborate the meaning about that @riskpp ?

It's from 3rd point in [In-app chat quick start guide]( https://www.infobip.com/docs/live-chat/mobile-in-app-chat-quick-start ). Please provide us information did you followed it or not?

**Comment by mrdafian47** [comment]
Hi @riskpp , thank you very much for your help and instruction...
I just realized, my missing step is registering my apps ini live chat...

Here the step that i missing...
```
Link the mobile application profile with the widget configuration: APPS > Live Chat > YOUR WIDGET > Audience & Availability > Mobile Application
```
