### ISSUE TITLE
Activity-alias crash on NotificationSettings.Builder(context).build()

### ISSUE THREAD

**Issue by alexkowlew** [infobip/mobile-messaging-sdk-android#37]
Hello, 

We found crash on library initialization after applying `activity-aliases`.

- infobip-mobile-messaging-android-sdk:6.4.1@aar
- Android OS: all

This issue is also reproduces on newer versions of the SDK

Here are the stack trace: 

```
java.lang.IllegalArgumentException: callbackActivity is mandatory! You should use the activity that will display received messages.
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6717)
        at android.app.ActivityThread.access$1300(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.IllegalArgumentException: callbackActivity is mandatory! You should use the activity that will display received messages.
        at org.infobip.mobile.messaging.NotificationSettings.setCallbackActivity(NotificationSettings.java:50)
        at org.infobip.mobile.messaging.NotificationSettings.-$$Nest$msetCallbackActivity(Unknown Source:0)
        at org.infobip.mobile.messaging.NotificationSettings$Builder.build(NotificationSettings.java:436)
        at org.infobip.mobile.messaging.MobileMessaging$Builder.loadNotificationSettings(MobileMessaging.java:512)
        at org.infobip.mobile.messaging.MobileMessaging$Builder.<init>(MobileMessaging.java:504)
        at org.kodein.di.bindings.Singleton$getFactory$1$1$1.invoke(standardBindings.kt:130)
        at org.kodein.di.bindings.SingletonReference.make(references.kt:34)
        at org.kodein.di.bindings.Singleton$getFactory$1$1.invoke(standardBindings.kt:130)
        at org.kodein.di.bindings.Singleton$getFactory$1$1.invoke(standardBindings.kt:98)
        at org.kodein.di.bindings.StandardScopeRegistry.getOrCreate(scopes.kt:65)
        at org.kodein.di.bindings.Singleton$getFactory$1.invoke(standardBindings.kt:130)
        at org.kodein.di.bindings.Singleton$getFactory$1.invoke(standardBindings.kt:98)
        at org.kodein.di.KodeinContainer$provider$$inlined$toProvider$1.invoke(curry.kt:14)
        at org.kodein.di.internal.DKodeinBaseImpl.Instance(DKodeinImpl.kt:30)
```

Thanks

**Comment by riskpp** [comment]
Hello @Beohrn,

Could you please provide the example of how and where are you starting Mobile Messaging SDK (where and with which parameters `MobileMessaging.Builder` and `NotificationSettings.Builder` are called), and example of android manifest setup with activity alias, so we could start investigation.

Thank you!

**Comment by alexkowlew** [comment]
Hello @riskpp

You can check out the following repository https://github.com/alexkowlew/ChangeAppIconWithInfobip. This repository represents Infobip SDK usage in our project.

After enabling `activity-alias` with a different app icon and launching the application, infobip will crash.

Thanks

**Comment by alexkowlew** [comment]
Hello @riskpp

You can check out the following repository https://github.com/alexkowlew/ChangeAppIconWithInfobip. This repository represents Infobip SDK usage in our project.

After enabling activity-alias with a different app icon and launching the application, infobip will crash.

Thanks

**Comment by acikul** [comment]
Hey @alexkowlew, 

Thank you for you patience and providing the repo with the code of your particular use case. It really helped in testing!

SDK version [8.4.1](https://github.com/infobip/mobile-messaging-sdk-android/releases/tag/8.4.1) should fix the crash.

If any other issues arise, feel free to report them.

Best regards!

**Comment by alexkowlew** [comment]
Hello @acikul,

This is great news. 

Thanks
