### ISSUE TITLE
Certificate issue while enable notification

### ISSUE THREAD

**Issue by kavathiyamahesh** [infobip/mobile-messaging-sdk-android#7]
Hello team,

While activate notification I am facing below error due to the certificate.

```
{
      "cancelled": false,
      "error": {
        "code": "-4",
        "cause": {
          "cause": {
            "cause": {
              "certPath": {
                "mCertificates": [
                  {
                    "notAfter": "Dec 1, 2020 05:30:00",
                    "notBefore": "Aug 29, 2018 05:30:00",
                    "type": "X.509"
                  },
                  {
                    "notAfter": "Aug 16, 2047 16:11:43",
                    "notBefore": "Jan 1, 2000 05:30:00",
                    "type": "X.509"
                  }
                ],
                "type": "X.509"
              },
              "index": -1,
              "detailMessage": "Trust anchor for certification path not found.",
              "stackTrace": [],
              "suppressedExceptions": []
            },
            "detailMessage": "java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.",
            "stackTrace": [],
            "suppressedExceptions": []
          },
          "detailMessage": "java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.",
          "stackTrace": [],
          "suppressedExceptions": []
        },
        "detailMessage": "Can\u0027t access URI : https://mobile.infobip.com/mobile/1/appinstance",
        "stackTrace": [],
        "suppressedExceptions": []
      },
      "inputs": []
    }
```

Error Logs : 

```
MobileMessaging: CREATE INSTALLATION ERROR <<<
org.infobip.mobile.messaging.api.support.ApiIOException: -4, Can't access URI : https://mobile.infobip.com/mobile/1/appinstance
        at org.infobip.mobile.messaging.api.support.http.client.DefaultApiClient.execute(DefaultApiClient.java:190)
        at org.infobip.mobile.messaging.api.support.Generator$CachingInvocationHandler.invoke(Generator.java:357)
        at java.lang.reflect.Proxy.invoke(Proxy.java:397)
        at $Proxy5.createInstance(Unknown Source)
        at org.infobip.mobile.messaging.mobile.appinstance.InstallationSynchronizer$1.run(InstallationSynchronizer.java:136)
        at org.infobip.mobile.messaging.mobile.appinstance.InstallationSynchronizer$1.run(InstallationSynchronizer.java:125)
        at org.infobip.mobile.messaging.mobile.common.MRetryableTask$1.run(MRetryableTask.java:82)
        at org.infobip.mobile.messaging.mobile.common.MAsyncTask$2.doInBackground(MAsyncTask.java:54)
        at org.infobip.mobile.messaging.mobile.common.MAsyncTask$2.doInBackground(MAsyncTask.java:42)
        at android.os.AsyncTask$2.call(AsyncTask.java:292)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
        at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(:com.google.android.gms@15090011@15.0.90 (020406-231259764):43)
        at com.android.okhttp.Connection.upgradeToTls(Connection.java:201)
        at com.android.okhttp.Connection.connect(Connection.java:155)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:282)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:216)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:392)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:107)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:218)
        at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
        at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:25)
        at org.infobip.mobile.messaging.api.support.http.client.DefaultApiClient.execute(DefaultApiClient.java:133)
        at org.infobip.mobile.messaging.api.support.Generator$CachingInvocationHandler.invoke(Generator.java:357) 
        at java.lang.reflect.Proxy.invoke(Proxy.java:397) 
        at $Proxy5.createInstance(Unknown Source) 
        at org.infobip.mobile.messaging.mobile.appinstance.InstallationSynchronizer$1.run(InstallationSynchronizer.java:136) 
        at org.infobip.mobile.messaging.mobile.appinstance.InstallationSynchronizer$1.run(InstallationSynchronizer.java:125) 
        at org.infobip.mobile.messaging.mobile.common.MRetryableTask$1.run(MRetryableTask.java:82) 
        at org.infobip.mobile.messaging.mobile.common.MAsyncTask$2.doInBackground(MAsyncTask.java:54) 
        at org.infobip.mobile.messaging.mobile.common.MAsyncTask$2.doInBackground(MAsyncTask.java:42) 
        at android.os.AsyncTask$2.call(AsyncTask.java:292) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:818) 
     Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
        at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:324)
        at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:225)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.google.android.gms.org.conscrypt.Platform.checkTrusted(:com.google.android.gms@15090011@15.0.90 (020406-231259764):2)
        at com.google.android.gms.org.conscrypt.Platform.checkServerTrusted(:com.google.android.gms@15090011@15.0.90 (020406-231259764):3)
        at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.verifyCertificateChain(:com.google.android.gms@15090011@15.0.90 (020406-231259764):12)
        at com.google.android.gms.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
        at com.google.android.gms.org.conscrypt.NativeSsl.doHandshake(:com.google.android.gms@15090011@15.0.90 (020406-231259764):7)
        at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(:com.google.android.gms@15090011@15.0.90 (020406-231259764):14)
        at com.android.okhttp.Connection.upgradeToTls(Connection.java:201) 
        at com.android.okhttp.Connection.connect(Connection.java:155) 
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:282) 
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:216) 
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:392) 
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:107) 
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:218) 
        at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218) 
        at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:25) 
        at org.infobip.mobile.messaging.api.support.http.client.DefaultApiClient.execute(DefaultApiClient.java:133) 
        at org.infobip.mobile.messaging.api.support.Generator$CachingInvocationHandler.invoke(Generator.java:357) 
        at java.lang.reflect.Proxy.invoke(Proxy.java:397) 
        at $Proxy5.createInstance(Unknown Source) 
        at org.infobip.mobile.messaging.mobile.appinstance.InstallationSynchronizer$1.run(InstallationSynchronizer.java:136) 
        at org.infobip.mobile.messaging.mobile.appinstance.InstallationSynchronizer$1.run(InstallationSynchronizer.java:125) 
        at org.infobip.mobile.messaging.mobile.common.MRetryableTask$1.run(MRetryableTask.java:82) 
        at org.infobip.mobile.messaging.mobile.common.MAsyncTask$2.doInBackground(MAsyncTask.java:54) 
        at org.infobip.mobile.messaging.mobile.common.MAsyncTask$2.doInBackground(MAsyncTask.java:42) 
        at android.os.AsyncTask$2.call(AsyncTask.java:292) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:818) 
     Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
        at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:324) 
        at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:225) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.google.android.gms.org.conscrypt.Platform.checkTrusted(:com.google.android.gms@15090011@15.0.90 (020406-231259764):2) 
        at com.google.android.gms.org.conscrypt.Platform.checkServerTrusted(:com.google.android.gms@15090011@15.0.90 (020406-231259764):3) 
        at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.verifyCertificateChain(:com.google.android.gms@15090011@15.0.90 (020406-231259764):12) 
        at com.google.android.gms.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method) 
        at com.google.android.gms.org.conscrypt.NativeSsl.doHandshake(:com.google.android.gms@15090011@15.0.90 (020406-231259764):7) 
        at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(:com.google.android.gms@15090011@15.0.90 (020406-231259764):14) 
        at com.android.okhttp.Connection.upgradeToTls(Connection.java:201) 
        at com.android.okhttp.Connection.connect(Connection.java:155) 
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:282) 
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:216) 
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:392) 
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:107) 
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:218) 
        at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218) 
        at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:25) 
        at org.infobip.mobile.messaging.api.support.http.client.DefaultApiClient.execute(DefaultApiClient.java:133) 
        at org.infobip.mobile.messaging.api.support.Generator$CachingInvocationHandler.invoke(Generator.java:357) 
        at java.lang.reflect.Proxy.invoke(Proxy.java:397) 
        at $Proxy5.createInstance(Unknown Source) 
        at org.infobip.mobile.messaging.mobile.appinstance.InstallationSynchronizer$1.run(InstallationSynchronizer.java:136) 
        at org.infobip.mobile.messaging.mobile.appinstance.InstallationSynchronizer$1.run(InstallationSynchronizer.java:125) 
        at org.infobip.mobile.messaging.mobile.common.MRetryableTask$1.run(MRetryableTask.java:82) 
        at org.infobip.mobile.messaging.mobile.common.MAsyncTask$2.doInBackground(MAsyncTask.java:54) 
        at org.infobip.mobile.messaging.mobile.common.MAsyncTask$2.doInBackground(MAsyncTask.java:42) 
        at android.os.AsyncTask$2.call(AsyncTask.java:292) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:818)
```

So I am not able to enable notification of few devices, it's work fines with few devices like Pixel 2, Samsung Galaxy S8, One plus X but not working with Nexus 6P and oppo and other devices. so please request you to resolve ASAP.

Thanks.

**Comment by stanislavin** [comment]
We are checking for potential certificate problems on our servers, but https://www.digicert.com/help/ reports that it is all good so far for https://mobile.infobip.com/. We will let you know.

**Comment by stanislavin** [comment]
By the callstack I see that it fails at `com.google.android.gms` and AFAIR you are using gcm still, so it might be related to outdated dependencies, if you can check with new versions please do.

**Comment by kavathiyamahesh** [comment]
Ok, let me check with that and update you. Thanks @stanislavin

**Comment by kavathiyamahesh** [comment]
Hello @stanislavin 

Looks like it's resolved after converting into FCM, will notify you if I am facing issues after FCM.

Thanks

**Comment by stanislavin** [comment]
Closing.

**Comment by kavathiyamahesh** [comment]
Hello @stanislavin

Still we are facing same issue after upgrading to FCM. 

Same logs getting as provided before.

**Comment by stanislavin** [comment]
I reopened the issue. It seems that on some devices the CA information is missing for the certificates used on our servers, this is a known problem in Android world and happens sometimes due to platform fragmentation. We will see about fixing it in some way, probably something like: https://developer.android.com/training/articles/security-ssl#UnknownCa. I will post and update here once we have a bugfix.

In the meantime - do you have a device in your hands where the issue is 100% reproducible?

**Comment by Jezzdev** [comment]
hello @stanislavin 
Yes, Its reproducible for couple of devices we are testing. Here is the information:
1. Nexus 6 (Android 7.0)
2. Oppo F1s(Android - 5.1)
3. LG g3 (Android 5.1)
Btw, I am working along with @kavathiyamahesh on same issue :)

**Comment by kavathiyamahesh** [comment]
Hello @stanislavin 

Any update on this ticket? it's a bit urgent from our side to fix this asap.

**Comment by stanislavin** [comment]
@kavathiyamahesh we have a task in progress about this. You can expect an update by end of this week.

**Comment by stanislavin** [comment]
Hotfix version `2.0.9.1` was released with the bugfix.
Initialize the SDK with specific setting to be able to connect on those devices:
`new MobileMessaging.Builder(this)
                .withHttpSettings(true)
                .build();`

Please test and let us know if works.

**Comment by kavathiyamahesh** [comment]
Hello @stanislavin 

That hotfix version you provided, While Initialize the SDK application getting crash. If I remove **withHttpSettings(true)** then also the application is crashing.
Please find crash logs.

```
VERSION <<<
{
      "libraryVersion": "2.0.9",
      "platformType": "GCM",
      "updateUrl": "https://github.com/infobip/mobile-messaging-sdk-android"
    }
 FATAL EXCEPTION: main
    java.lang.IllegalArgumentException: class org.infobip.mobile.messaging.mobile.version.a declares multiple JSON fields named a
        at org.infobip.mobile.messaging.api.shaded.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(SourceFile:170)
        at org.infobip.mobile.messaging.api.shaded.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(SourceFile:100)
        at org.infobip.mobile.messaging.api.shaded.google.gson.Gson.getAdapter(SourceFile:423)
        at org.infobip.mobile.messaging.api.shaded.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(SourceFile:56)
        at org.infobip.mobile.messaging.api.shaded.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(SourceFile:125)
        at org.infobip.mobile.messaging.api.shaded.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(SourceFile:243)
        at org.infobip.mobile.messaging.api.shaded.google.gson.Gson.toJson(SourceFile:669)
        at org.infobip.mobile.messaging.api.shaded.google.gson.Gson.toJson(SourceFile:648)
        at org.infobip.mobile.messaging.api.shaded.google.gson.Gson.toJson(SourceFile:603)
        at org.infobip.mobile.messaging.api.shaded.google.gson.Gson.toJson(SourceFile:583)
        at org.infobip.mobile.messaging.logging.MobileMessagingLogger.objectToPrettyString(SourceFile:133)
        at org.infobip.mobile.messaging.logging.MobileMessagingLogger.a(SourceFile:138)
        at org.infobip.mobile.messaging.logging.MobileMessagingLogger.v(SourceFile:49)
        at org.infobip.mobile.messaging.mobile.common.MAsyncTask$2.a(SourceFile:65)
        at org.infobip.mobile.messaging.mobile.common.MAsyncTask$2.onPostExecute(SourceFile:42)
        at android.os.AsyncTask.finish(AsyncTask.java:695)
        at android.os.AsyncTask.access$600(AsyncTask.java:180)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7045)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
```
One thing, I have noticed that even I am using version **2.0.9.1** still it's showing **2.0.9** in logs. Also we are using FCM, I don't know why it's showing platformType=**GCM**

**Comment by stanislavin** [comment]
Sounds like a proguard issue. If it is urgent, you can try adding lines from SDK proguard file to see it helps.
https://github.com/infobip/mobile-messaging-sdk-android/blob/master/infobip-mobile-messaging-android-sdk/proguard-rules.pro

**Comment by kavathiyamahesh** [comment]
Ok thanks for the quick update, Let me check and get back to you.

**Comment by kavathiyamahesh** [comment]
Hello @stanislavin 

I have applied pro-guard which you mentioned in the link still I am getting the same error.

I have tried without pro-guard and looks like the issue is fixed still I am not sure it will work with pro-guard or not, so please fix above error so I can double confirm from my side.

Thanks

**Comment by stanislavin** [comment]
Added fix to baseline and released 2.0.10, please recheck

**Comment by kavathiyamahesh** [comment]
Thanks @stanislavin 
Looks like issues is fixed, but we will inform you once our testing team approves this fix.
Thank you so much for your efforts, Appreciate it..!!!

**Comment by kavathiyamahesh** [comment]
Hello @stanislavin 
Thanks for waiting, We got an update from our testing team and push notification is working fine.
So we can close this ticket and will re-open or create new if required in the future.

Thanks
