### ISSUE TITLE
Getting Installation error

### ISSUE THREAD

**Issue by kavathiyamahesh** [infobip/mobile-messaging-sdk-android#9]
Hello

I am facing installation error while adding attributes on the infobip portal. please check logs.

```
MobileMessaging: UPDATE INSTALLATION ERROR <<<
    org.infobip.mobile.messaging.api.support.ApiException: -3, Unknown API error
        at org.infobip.mobile.messaging.api.support.http.client.DefaultApiClient.executeHTTP(DefaultApiClient.java:197)
        at org.infobip.mobile.messaging.api.support.http.client.DefaultApiClient.execute(DefaultApiClient.java:89)
        at org.infobip.mobile.messaging.api.support.Generator$CachingInvocationHandler.invoke(Generator.java:368)
        at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
        at $Proxy2.patchInstance(Unknown Source)
        at org.infobip.mobile.messaging.mobile.appinstance.InstallationSynchronizer$2.run(InstallationSynchronizer.java:209)
        at org.infobip.mobile.messaging.mobile.appinstance.InstallationSynchronizer$2.run(InstallationSynchronizer.java:205)
        at org.infobip.mobile.messaging.mobile.common.MRetryableTask$1.run(MRetryableTask.java:82)
        at org.infobip.mobile.messaging.mobile.common.MAsyncTask$2.doInBackground(MAsyncTask.java:54)
        at org.infobip.mobile.messaging.mobile.common.MAsyncTask$2.doInBackground(MAsyncTask.java:42)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by stanislavin** [comment]
Hi @kavathiyamahesh can you please provide some logs before this error, logcat should also have some lines like
```
MobileMessaging: UPDATE INSTALLATION >>>
```
and then description of request.

Thx

**Comment by kavathiyamahesh** [comment]
Hello @stanislavin 

```
D/MMHTTP: REQUEST: Request(httpMethod=PATCH, uri=https://mobile.infobip.com/mobile/1/appinstance/a1ce53ae-d60d-440c-be07-88365b888261, apiKey=49ad70d1d8d480a2bba4e76808bd616d-1043c61c-aa34-46a1-ac7c-1fee547aae3f, credentials=null, headers={applicationcode=[5142d8416a], pushregistrationid=[a1ce53ae-d60d-440c-be07-88365b888261], foreground=[true]}, queryParams={}, body={regEnabled=true, pushServiceToken=eRQ-W12V2w0:APA91bHxe_qKpiIpjMPCnvQSPgM5Bpm3XCKfHnYmrGXvW41pVW4EKAakP4EySrhiU-n5tRLg70jlwb2r35o4DzRjYxA0x7VEHl_19jNqnzEVQMcj7wJOtl9AaDKyX66d2yTAs4fiYVUs})
```

**Comment by kavathiyamahesh** [comment]
@stanislavin  One more log might be this will be helpful for you.

```
D/MMHTTP: REQUEST: Request(httpMethod=PATCH, uri=https://mobile.infobip.com/mobile/1/appinstance/c60da47a-4ac6-4837-89d3-ac0435e30057, apiKey=49ad70d1d8d480a2bba4e76808bd616d-1043c61c-aa34-46a1-ac7c-1fee547aae3f, credentials=null, headers={applicationcode=[5142d8416a], pushregistrationid=[c60da47a-4ac6-4837-89d3-ac0435e30057], foreground=[true]}, queryParams={}, body={regEnabled=true, customAttributes={service-notification=true, transactions-notifications=true}})
```
Thanks

**Comment by kavathiyamahesh** [comment]
Hello @stanislavin Any updates? 
Thanks

**Comment by stanislavin** [comment]
It was a server-side misconfiguration and was fixed recently. Please retest and let us know if works.

**Comment by kavathiyamahesh** [comment]
Thanks @stanislavin 
I just checked and it's working fine now.
